--- 

- hosts: web
  name: "WebServer Deployment Play"
  become: yes
  become_method: sudo 
  tasks: 
  - name: Install Required Web Packages
    yum: name=httpd state=present

  - name: Start the HTTPD Service 
    service: name=httpd state=started 

  - name: Download Required Image
    get_url: url="https://www.mariomayhem.com/downloads/wallpapers/7/nsmb_wp7_1280.jpg"  dest=/var/www/html/mario.jpg mode=0755

  - name: Deploy a Web Template
    template: src=templates/info.j2 dest=/var/www/html/info.html      



- hosts: all
  name: "NTP Server Deployment Play"
  become: yes
  become_method: sudo 
  tasks: 
  - name: Install Required NTP Packages
    yum: name=ntp state=present

  - name: Start the NTPD Service 
    service: name=ntpd state=started